set nocompatible
set number
set backspace=2
set tabstop=4
set ignorecase
set hlsearch
set sw=4
set cursorline
set ruler 
set nobackup
set autochdir
set backupcopy=yes
set smartindent
set laststatus=2
set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ Ln\ %l,\ Col\ %c/%L%)
set matchtime=2
setlocal noswapfile
set clipboard=unnamed
colorscheme evening
let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
let Tlist_Use_Right_Window=1
set tags=tags;
set autochdir
syntax on
